
-- 1. What is the average age of customers?
SELECT AVG(age) AS average_age 
FROM customer_data;

-- 2. What is the gender distribution of customers?
SELECT gender, COUNT(*) AS count 
FROM customer_data 
GROUP BY gender;

-- 3. What is the average income of customers?
SELECT AVG(income) AS average_income 
FROM customer_data;

-- 4. How does income vary by gender?
SELECT gender, AVG(income) AS average_income 
FROM customer_data 
GROUP BY gender;

-- 5. What is the average spending score of customers?
SELECT AVG(spending_score) AS average_spending_score 
FROM customer_data;

-- 6. What is the total last purchase amount for all customers?
SELECT SUM(last_purchase_amount) AS total_last_purchase_amount FROM customer_data;

-- 7. What is the average last purchase amount for all customers?
SELECT AVG(last_purchase_amount) AS average_last_purchase_amount FROM customer_data;

-- 8. What is the average number of membership years?
SELECT AVG(membership_years) AS average_membership_years 
FROM customer_data;

-- 9. What is the average purchase frequency of customers?
SELECT AVG(purchase_frequency) AS average_purchase_frequency 
FROM customer_data;

-- 10. Which are the most popular preferred categories?
SELECT preferred_category, COUNT(*) AS count 
FROM customer_data 
GROUP BY preferred_category 
ORDER BY count DESC;

-- 11. What is the average spending score in each preferred category?
SELECT preferred_category, AVG(spending_score) AS average_spending_score 
FROM customer_data 
GROUP BY preferred_category;

-- 12. How many customers fall into each spending score range (low, medium, high)?
SELECT 
    CASE 
        WHEN spending_score < 40 THEN 'Low'
        WHEN spending_score BETWEEN 40 AND 70 THEN 'Medium'
        ELSE 'High'
    END AS spending_score_range, 
    COUNT(*) AS count
FROM customer_data
GROUP BY spending_score_range;

-- 13. What is the correlation between income and spending score?
SELECT CORR(income, spending_score) AS income_spending_score_corr FROM customer_data;

-- 14. What is the correlation between age and last purchase amount?
SELECT CORR(age, last_purchase_amount) AS age_last_purchase_corr FROM customer_data;

-- 15. Who are the top 10 customers based on their spending score?
SELECT * FROM customer_data 
ORDER BY spending_score DESC 
LIMIT 10;

-- 16. Who are the top 10 customers based on their last purchase amount?
SELECT * FROM customer_data 
ORDER BY last_purchase_amount DESC 
LIMIT 10;

-- 17. What are the characteristics of customers who have been members for more than 5 years?
SELECT * FROM customer_data 
WHERE membership_years > 5;

-- 18. What is the average last purchase amount for customers with high purchase frequency (e.g., more than 30 purchases)?
SELECT AVG(last_purchase_amount) AS average_last_purchase_amount FROM customer_data 
WHERE purchase_frequency > 30;

-- 19. What are the most preferred categories among high-income customers (e.g., income > $100,000)?
SELECT preferred_category, COUNT(*) AS count 
FROM customer_data 
WHERE income > 100000 
GROUP BY preferred_category 
ORDER BY count DESC;

-- 20. How does purchase frequency vary by preferred category?
SELECT preferred_category, AVG(purchase_frequency) AS average_purchase_frequency
FROM customer_data
GROUP BY preferred_category
ORDER BY preferred_category DESC;

-- 21. What is the total income generated by each preferred category?
SELECT preferred_category, SUM(income) AS total_income
FROM customer_data
GROUP BY preferred_category
ORDER BY total_income DESC;

-- 22. What is the average spending score of male vs. female customers?
SELECT gender, AVG(spending_score) AS average_spending_score 
FROM customer_data 
GROUP BY gender;

-- 23. How many customers have a spending score above 80?
SELECT COUNT(*) AS count 
FROM customer_data 
WHERE spending_score > 80;

-- 24. What is the distribution of membership years among customers?
SELECT membership_years, COUNT(*) AS customer_count
FROM customer_data
GROUP BY membership_years
ORDER BY membership_years;

-- 25. How does age influence spending score?
SELECT age, AVG(spending_score) AS average_spending_score
FROM customer_data
GROUP BY age
ORDER BY age;

-- 26. What is the total last purchase amount by gender?
SELECT gender, SUM(last_purchase_amount) AS total_last_purchase_amount
FROM customer_data
GROUP BY gender;

-- 27. What is the average income of customers with a spending score above 70?
SELECT AVG(income) AS avg_income
FROM customer_data
WHERE spending_score > 70;

-- 28. Which preferred category has the highest average last purchase amount?
SELECT preferred_category, AVG(last_purchase_amount) AS average_last_purchase_amount
FROM customer_data
GROUP BY preferred_category
ORDER BY average_last_purchase_amount DESC LIMIT 1;

-- 29. What is the distribution of last purchase amounts among customers?
SELECT last_purchase_amount, COUNT(*) AS count
FROM customer_data
GROUP BY last_purchase_amount
ORDER BY last_purchase_amount;

-- 30. How many customers have made more than 20 purchases in each preferred_category?
SELECT preferred_category ,COUNT(*) AS count 
FROM customer_data 
WHERE purchase_frequency > 20
GROUP BY preferred_category;

-- 31. What is the average age of customers in each preferred category?
SELECT preferred_category, AVG(age) AS average_age
FROM customer_data
GROUP BY preferred_category;

-- 32. How does spending score vary by purchase frequency?
SELECT purchase_frequency, AVG(spending_score) AS average_spending_score
FROM customer_data
GROUP BY purchase_frequency
ORDER BY purchase_frequency;

-- 33. What is the median last purchase amount for all customers?
SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY last_purchase_amount) AS median_last_purchase_amount
FROM customer_data;

-- 34. What percentage of customers have an income above $75,000?
SELECT (COUNT(*) FILTER (WHERE income > 75000) * 100.0 / COUNT(*)) AS percentage_above_75000 FROM customer_data;

-- 35. How does membership years correlate with purchase frequency?
SELECT CORR(membership_years, purchase_frequency) AS membership_years_purchase_frequency_corr FROM customer_data;

-- 36. What is the average purchase frequency of male vs. female customers?
SELECT gender, AVG(purchase_frequency) AS average_purchase_frequency 
FROM customer_data 
GROUP BY gender;

-- 37. Which preferred category has the highest spending score?
SELECT preferred_category, AVG(spending_score) AS average_spending_score
FROM customer_data
GROUP BY preferred_category
ORDER BY average_spending_score DESC LIMIT 1;

----------------------------------------------------------------

SELECT preferred_category, spending_score
FROM customer_data
WHERE spending_score = (SELECT MAX(spending_score) FROM customer_data)

-- 38. How many customers have an income below $50,000?
SELECT COUNT(*) AS count 
FROM customer_data 
WHERE income < 50000;

-- 39. What is the total spending score of all customers combined?
SELECT SUM(spending_score) AS total_spending_score 
FROM customer_data;

-- 40. What is the distribution of purchase frequency among customers?
SELECT purchase_frequency, COUNT(*) AS customer_count
FROM customer_data
GROUP BY purchase_frequency
ORDER BY customer_count DESC;

-- 41. How many customers have been members for more than 10 years?
SELECT COUNT(*) AS count 
FROM customer_data 
WHERE membership_years > 10;

-- 42. What is the average last purchase amount for each gender?
SELECT gender, AVG(last_purchase_amount) AS average_last_purchase_amount 
FROM customer_data 
GROUP BY gender;

-- 43. How many customers are under the age of 30?
SELECT COUNT(*) AS count 
FROM customer_data 
WHERE age < 30;

-- 44. What is the average income of customers in the 'Groceries' category?
SELECT AVG(income) AS average_income 
FROM customer_data 
WHERE preferred_category = 'Groceries';

-- 45. How does the average spending score vary by age group (e.g., 20-30, 31-40)?
SELECT 
    CASE
        WHEN age <= 20 THEN 'Younger' 
        WHEN age BETWEEN 21 AND 30 THEN '21-30'
        WHEN age BETWEEN 31 AND 40 THEN '31-40'
        WHEN age BETWEEN 41 AND 50 THEN '41-50'
        WHEN age BETWEEN 51 AND 60 THEN '51-60'
        ELSE 'Other'
    END AS age_group, 
    AVG(spending_score) AS average_spending_score
FROM customer_data
GROUP BY age_group;

-- 46. What is the highest last purchase amount recorded?
SELECT MAX(last_purchase_amount) AS highest_last_purchase_amount FROM customer_data;

-- 47. What is the lowest income recorded in the dataset?
SELECT MIN(income) AS lowest_income 
FROM customer_data;

-- 48. How many customers have a spending score of exactly 50?
SELECT COUNT(*) AS count 
FROM customer_data 
WHERE spending_score = 50;

-- 49. What is the total number of purchases made by all customers combined?
SELECT SUM(purchase_frequency) AS total_number_of_purchases FROM customer_data;

-- 50. What is the average membership years for customers with a spending score above 60?
SELECT AVG(membership_years) AS average_membership_years FROM customer_data WHERE spending_score > 60;

----------------------------------------------------------------

-- more complex queries

-- 51. Identify the top 5 preferred categories with the highest average income and the number of customers in those categories.

SELECT preferred_category, AVG(income) as avg_income, COUNT(*) AS customer_count
FROM customer_data
GROUP BY preferred_category
ORDER BY avg_income DESC
LIMIT 5;

-- 52. Calculate the cumulative sum of spending scores for each preferred category, ordered by the highest cumulative sum.

WITH cumulative_spending AS (
    SELECT preferred_category, SUM(spending_score) AS total_spending_score
    FROM customer_data
    GROUP BY preferred_category
)
SELECT preferred_category, total_spending_score
FROM cumulative_spending
ORDER BY total_spending_score DESC;

----------------------------------------------------------------

SELECT preferred_category, SUM(spending_score) AS total_spending_score
FROM customer_data
GROUP BY preferred_category
ORDER BY total_spending_score DESC;

-- 53.  Find the top 5 customers who have the highest last purchase amount and have been members for more than 5 years.

SELECT *
FROM customer_data
WHERE membership_years > 5
ORDER BY last_purchase_amount DESC
LIMIT 5;

-- 54. Calculate the average spending score for customers who have an income above the average income and categorize them by preferred category.

WITH avg_income AS (
    SELECT AVG(income) AS average_income
    FROM customer_data
)

SELECT preferred_category, AVG(spending_score) as average_spending_score
FROM customer_data, avg_income
WHERE income > avg_income.average_income
GROUP BY preferred_category
ORDER BY average_spending_score;

-- 55.  Determine the year-over-year growth rate of the total last purchase amount.

WITH yearly_data AS (
    SELECT EXTRACT(YEAR FROM CURRENT_DATE) - membership_years AS year, SUM(last_purchase_amount) AS total_last_purchase_amount
    FROM customer_data
    GROUP BY year
)

SELECT year, total_last_purchase_amount,
    (total_last_purchase_amount - LAG
    (total_last_purchase_amount) OVER (ORDER BY year)) / NULLIF
    (LAG(total_last_purchase_amount) OVER (ORDER BY year), 0
    ) * 100 AS growth_rate
FROM yearly_data
ORDER BY year;

-- 56. Identify customers who have a higher spending score than the average spending score in their preferred category.

WITH category_avg_spending AS (
    SELECT preferred_category, AVG(spending_score) AS average_spending_score
    FROM customer_data
    GROUP BY preferred_category
)

SELECT c.*
FROM customer_data c
JOIN category_avg_spending cas ON c.preferred_category = cas.preferred_category
WHERE c.spending_score > cas.average_spending_score

-- 57.  Find the preferred category with the highest variance in spending score.

SELECT preferred_category, VARIANCE(spending_score) AS spending_score_variance
FROM customer_data
GROUP BY preferred_category
ORDER BY spending_score_variance DESC
LIMIT 1;

-- 58. Calculate the percentage contribution of each preferred category to the total last purchase amount.

WITH total_last_purchase_amount AS (
    SELECT SUM(last_purchase_amount) AS total_last_purchase_amount
    FROM customer_data
)

SELECT preferred_category, SUM(last_purchase_amount) AS category_last_purchase_amount, (SUM(last_purchase_amount) * 100.0 / (SELECT total_last_purchase_amount FROM total_last_purchase_amount)) AS percentage_contribution
FROM customer_data
GROUP BY preferred_category
ORDER BY category_last_purchase_amount DESC;


-- 59. Find the top 3 age groups with the highest average income, where age groups are categorized as 20-30, 31-40, 41-50, and above 50.

SELECT 
    CASE 
        WHEN age BETWEEN 20 AND 30 THEN '20-30'
        WHEN age BETWEEN 31 AND 40 THEN '31-40'
        WHEN age BETWEEN 41 AND 50 THEN '41-50'
        ELSE '51 and above'
    END AS age_group, 
    AVG(income) AS average_income
FROM customer_data
GROUP BY age_group
ORDER BY average_income DESC
LIMIT 3;


-- 60. Identify the customers who fall into the top 10% of both income and spending score.

WITH income_percentile AS (
    SELECT PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY income) AS p90_income
    FROM customer_data
),
spending_score_percentile AS (
    SELECT PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY spending_score) AS p90_spending_score
    FROM customer_data
)
SELECT c.*
FROM customer_data c
WHERE c.income >= (SELECT p90_income FROM income_percentile)
AND c.spending_score >= (SELECT p90_spending_score FROM spending_score_percentile);


